on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build --progress=plain --no-cache -t python-lambda .
      - run: docker run --entrypoint /bin/ls python-lambda -l /app/.venv/lib/python3.9/site-packages/jira/__init__.py
      - run: docker run --entrypoint /app/.venv/bin/python -c 'from jira import JIRA'
  native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
      - run: pip install "poetry==1.6.1"
      - run: poetry config virtualenvs.in-project true
      - run: poetry install --no-interaction --no-ansi -vvv
      - run: ls -l .venv/lib/python3.9/site-packages/jira/__init__.py
      - run: .venv/bin/python -c 'from jira import JIRA'